spring.application.name=hireai-backend

# DATABASE
spring.datasource.url=jdbc:postgresql://localhost:5432/hireAI
spring.datasource.username=postgres
spring.datasource.password=matrix20122002

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect


# mailing

spring.mail.host=smtp-relay.brevo.com
spring.mail.port=587

spring.mail.username=doumou159@gmail.com
spring.mail.password=phAZPCndcG4vbNE0
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true


# JWT
jwt.secret=${JWT_SECRET:hireai-local-development-jwt-secret-change-in-production}
jwt.expiration=86400000
